version: '3.4'

services:
  student:
    build:
      context: ./
      dockerfile: ./docker/student/Dockerfile
    image: student_server:${GITHASH}
    container_name: student
    ports:
      - 8071:80
    networks: 
      - eknet  
    restart: "always"
    volumes:
      - neuget:/var/negut:rw
  admin:
    build:
      context: ./
      dockerfile: ./docker/admin/Dockerfile
    image: admin_server:${GITHASH}
    container_name: admin
    ports:
      - 8072:80
    networks: 
      - eknet
    restart: "always"
    volumes:
      - neuget:/var/negut:rw
  teacher:
    build: 
      context: ./
      dockerfile: ./docker/teacher/Dockerfile
    image: teacher_server:${GITHASH}
    container_name: teacher
    ports:
      - 8073:80
    networks:
      - eknet
    restart: "always"
    volumes:
      - neuget:/var/negut:rw

volumes: 
  neuget:

networks: # 创建新的网络类型
  eknet:
    driver: bridge  # 网络方式：桥接或集群